# 工作流名称
name: sponsors

on:
  push:
    branches: [ main ]

  # 当 star 当前仓库时立即执行
  watch:
    types: [started]

  # 增加一份定时任务，具体时间可任意指定
  schedule:
    # UTC 00:00 和 UTC 12:00
    - cron: '0 0,12 * * *'

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install package
        run: npm install

      - name: Update sponsors
        # 使用sponsorkit工具生成Sponsors图片到根目录
        run: npx sponsorkit -f -w 800 --dir . && npx sponsorkit -f -w 1300 --name sponsors.wide --dir .
        env:
          # 使用仓库内配置好的Token
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}

      - name: Commit
        uses: EndBug/add-and-commit@v4
        with:
          # 提交信息
          message: "chore: update sponsors.svg"
          # 提交内容
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
